name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Configure project with CMake
        run: |
          cmake -S . -B build

      - name: Build project
        run: |
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
